{% set name = "compas_libigl" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/pybind/pybind11/archive/v2.5.0.tar.gz
    folder: $RECIPE_DIR/../thirdparty/pybind11
    fn: pybind11-2.5.0.tar.gz
    sha256: 97504db65640570f32d3fdf701c25a340c8643037c3b69aec469c10c93dc8504
  - url: https://github.com/libigl/libigl/archive/v2.2.0.tar.gz
    folder: $RECIPE_DIR/../thirdparty/libigl
    fn: libigl-2.2.0.tar.gz
    sha256: b336e548d718536956e2d6958a0624bc76d50be99039454072ecdc5cf1b2ede5
  - path: $RECIPE_DIR/../../

#   - url: https://github.com/blockresearchgroup/compas_libigl/archive/v0.1.0.tar.gz
#     fn: compas_libigl-0.1.0.tar.gz
#     sha256: b336e548d718536956e2d6958a0624bc76d50be99039454072ecdc5cf1b2ede5

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  build:
    - git
    - cmake
    - boost
    - eigen
  host:
    - python
    - pip
  run:
    - COMPAS >=0.15.5

test:
  imports:
    - compas_libigl

about:
  home: https://github.com/blockresearchgroup/compas_libigl
  license: GPL
  summary: 'COMPAS friendly wrappers for libigl functions.'
  dev_url: https://github.com/blockresearchgroup/compas_libigl
  doc_url: https://blockresearchgroup.github.io/compas_libigl
  doc_source_url: https://github.com/blockresearchgroup/compas_libigl/blob/master/README.rst

extra:
  recipe-maintainers:
    - brgcode
