{% set name = "compas_libigl" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # git_url: https://github.com/BlockResearchGroup/compas_libigl.git
  # git_depth: 1
  # url: https://github.com/blockresearchgroup/compas_libigl/archive/alpha-{{ version }}.tar.gz
  # sha256: f90b39d88ea003bc2ca7925146babb20320cedebe096e4c276835490be8e10a0
  # git_url: ../
  path: $RECIPE_DIR/../../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  # script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv"

requirements:
  build:
    - git
    - cmake
    - boost
  host:
    - python
    - pip
  run:
    - COMPAS >=0.15.5

test:
  imports:
    - compas_libigl

about:
  home: https://github.com/blockresearchgroup/compas_libigl
  license: GPL
  summary: 'COMPAS friendly wrappers for libigl functions.'
  dev_url: https://github.com/blockresearchgroup/compas_libigl
  doc_url: https://blockresearchgroup.github.io/compas_libigl
  doc_source_url: https://github.com/blockresearchgroup/compas_libigl/blob/master/README.rst

extra:
  recipe-maintainers:
    - brgcode
