name: test4
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - python.app  # [osx]
  - boost
  - eigen
  - cmake>=3.14
  - git
  - pip>=19.0
  - COMPAS>=0.15.6
  - PySide2  # [osx]
  - PyOpenGL  # [osx]
  - pip:
      - git+https://github.com/compas-dev/compas_viewers.git#egg=compas_viewers  # [osx]
