name: docs

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build and deploy docs
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: conda-incubator/setup-miniconda@v2.0.0
        with:
          miniconda-version: "latest"
          activate-environment: igl
          channels: conda-forge
          python-version: 3.8
      - name: build
        run: |
          conda install git cmake">=3.14" boost eigen=3.3 compas --yes
          pip install -r requirements-dev.txt
          invoke docs
      - uses: compas-dev/compas-actions.docs@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_conda: true
